<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup Label="gRPC / Protobuf">
    <PackageVersion Include="Google.Protobuf" Version="3.35.1" />
    <PackageVersion Include="Grpc.AspNetCore" Version="2.80.0" />
    <PackageVersion Include="Grpc.AspNetCore.Server.Reflection" Version="2.80.0" />
    <PackageVersion Include="Grpc.AspNetCore.Web" Version="2.80.0" />
    <PackageVersion Include="Grpc.Core.Api" Version="2.80.0" />
    <PackageVersion Include="Grpc.Tools" Version="2.82.0" />
    <PackageVersion Include="Grpc.Net.Client" Version="2.80.0" />
  </ItemGroup>
  <ItemGroup Label="Microsoft.Extensions">
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.9" />
  </ItemGroup>
  <ItemGroup Label="Testing">
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>