<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\simulator\TacticalApi.Simulator.Core\TacticalApi.Simulator.Core.csproj"/>
    <ProjectReference Include="..\..\src\simulator\TacticalApi.Simulator.Host\TacticalApi.Simulator.Host.csproj"/>
    <ProjectReference Include="..\..\src\adapter\TacticalApi.Simulator.Sources.Synthetic\TacticalApi.Simulator.Sources.Synthetic.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" PrivateAssets="all"/>
    <PackageReference Include="Grpc.Net.Client"/>
    <PackageReference Include="Grpc.Net.Client.Web"/>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="xunit"/>
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all"/>
  </ItemGroup>

</Project>
