<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TacticalApi.Simulator.Contracts\TacticalApi.Simulator.Contracts.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client"/>
    <PackageReference Include="Microsoft.Extensions.Hosting"/>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions"/>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions"/>
    <PackageReference Include="Microsoft.Extensions.Options"/>
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions"/>
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations"/>
    <PackageReference Include="Serilog.Extensions.Logging"/>
    <PackageReference Include="Serilog.Sinks.File"/>
  </ItemGroup>

</Project>
